import 'package:flutter/material.dart';
import 'package:redditech/screens/auth/auth.dart';
import 'package:redditech/screens/community/main_community_screen.dart';
import 'package:redditech/screens/home/main_home_screen.dart';
import 'package:redditech/screens/search/main_search_screen.dart';
import 'package:redditech/screens/profile/profile.dart';

// Constants of colors
const dark0 = Color(0xff15072C);
const dark1 = Color(0xff2A0E58);
const dark2 = Color(0xff3F1584);
const dark3 = Color(0xff541CB0);
const medium0 = Color(0xff6C27DD);
const medium1 = Color(0xff874DE5);
const medium2 = Color(0xffA376EF);
const medium3 = Color(0xffD0B8FA);
const light0 = Color(0xffF6F1FE);
const light1 = Color(0xffFCFAFF);
const neutralDark0 = Color(0xff212529);
const neutralDark1 = Color(0xff343A40);
const neutralDark2 = Color(0xff495057);
const neutralDark3 = Color(0xff6C757D);
const neutralMedium0 = Color(0xffADB5BD);
const neutralMedium1 = Color(0xffCED4DA);
const neutralMedium2 = Color(0xffDEE2E6);
const neutralMedium3 = Color(0xffE9ECEF);
const neutralLight0 = Color(0xffF8F9FA);

// Border radius for containers under the appbar
const containerBorder = BoxDecoration(
  color: Colors.white,
  borderRadius: BorderRadius.only(
    topLeft: Radius.circular(15),
    topRight: Radius.circular(15),
  ),
);

// Screens displayed in the bottom navbar
final bottomNavbarScreens = [
  const HomeScreen(),
  const CommunityScreen(),
  const AuthScreen(),
  const SearchScreen(),
  const Profile(),
];
// Titles displayed in the appbar
final title = [
  "Home",
  "My communities",
  "Add",
  "Search subbredit",
];

List<String> acceptPmsOptions = <String>['everyone', 'whitelisted'];
List<dynamic> langOptions = [
  {
    "tag": "af",
    "name": "Afrikaans",
    "nativeName": "Afrikaans",
  },
  {
    "tag": "am",
    "name": "አማርኛ",
    "nativeName": "Amharic",
  },
  {
    "tag": "ar",
    "name": "العربية",
    "nativeName": "Arabic",
  },
  {
    "tag": "arn",
    "name": "Mapudungun",
    "nativeName": "Mapudungun",
  },
  {
    "tag": "as",
    "name": "অসমীয়া",
    "nativeName": "Assamese",
  },
  {
    "tag": "az",
    "name": "Azərbaycan­lı",
    "nativeName": "Azerbaijani",
  },
  {
    "tag": "ba",
    "name": "Башҡорт",
    "nativeName": "Bashkir",
  },
  {
    "tag": "be",
    "name": "беларуская",
    "nativeName": "Belarusian",
  },
  {
    "tag": "bg",
    "name": "български",
    "nativeName": "Bulgarian",
  },
  {
    "tag": "bn",
    "name": "বাংলা",
    "nativeName": "Bengali",
  },
  {
    "tag": "bo",
    "name": "བོད་ཡིག",
    "nativeName": "Tibetan",
  },
  {
    "tag": "br",
    "name": "brezhoneg",
    "nativeName": "Breton",
  },
  {
    "tag": "bs",
    "name": "bosanski/босански",
    "nativeName": "Bosnian",
  },
  {
    "tag": "ca",
    "name": "català",
    "nativeName": "Catalan",
  },
  {
    "tag": "co",
    "name": "Corsu",
    "nativeName": "Corsican",
  },
  {
    "tag": "cs",
    "name": "čeština",
    "nativeName": "Czech",
  },
  {
    "tag": "cy",
    "name": "Cymraeg",
    "nativeName": "Welsh",
  },
  {
    "tag": "da",
    "name": "dansk",
    "nativeName": "Danish",
  },
  {
    "tag": "de",
    "name": "Deutsch",
    "nativeName": "German",
  },
  {
    "tag": "dolnoserbšćina",
    "name": "Sorbian",
    "nativeName": "Lower",
  },
  {
    "tag": "dv",
    "name": "ދިވެހިބަސް",
    "nativeName": "Divehi",
  },
  {
    "tag": "el",
    "name": "ελληνικά",
    "nativeName": "Greek",
  },
  {
    "tag": "en",
    "name": "English",
    "nativeName": "English",
  },
  {
    "tag": "es",
    "name": "español",
    "nativeName": "Spanish",
  },
  {
    "tag": "et",
    "name": "eesti",
    "nativeName": "Estonian",
  },
  {
    "tag": "eu",
    "name": "euskara",
    "nativeName": "Basque",
  },
  {
    "tag": "fa",
    "name": "فارسى",
    "nativeName": "Persian",
  },
  {
    "tag": "fi",
    "name": "suomi",
    "nativeName": "Finnish",
  },
  {
    "tag": "fil",
    "name": "Filipino",
    "nativeName": "Filipino",
  },
  {
    "tag": "fo",
    "name": "føroyskt",
    "nativeName": "Faroese",
  },
  {
    "tag": "fr",
    "name": "français",
    "nativeName": "French",
  },
  {
    "tag": "fy",
    "name": "Frysk",
    "nativeName": "Frisian",
  },
  {
    "tag": "ga",
    "name": "Gaeilge",
    "nativeName": "Irish",
  },
  {
    "tag": "Gàidhlig",
    "name": "Gaelic",
    "nativeName": "Scottish",
  },
  {
    "tag": "gl",
    "name": "galego",
    "nativeName": "Galician",
  },
  {
    "tag": "gsw",
    "name": "Elsässisch",
    "nativeName": "Alsatian",
  },
  {
    "tag": "gu",
    "name": "ગુજરાતી",
    "nativeName": "Gujarati",
  },
  {
    "tag": "ha",
    "name": "Hausa",
    "nativeName": "Hausa",
  },
  {
    "tag": "he",
    "name": "עברית",
    "nativeName": "Hebrew",
  },
  {
    "tag": "hi",
    "name": "हिंदी",
    "nativeName": "Hindi",
  },
  {
    "tag": "hr",
    "name": "hrvatski",
    "nativeName": "Croatian",
  },
  {
    "tag": "hornjoserbšćina",
    "name": "Sorbian",
    "nativeName": "Upper",
  },
  {
    "tag": "hu",
    "name": "magyar",
    "nativeName": "Hungarian",
  },
  {
    "tag": "hy",
    "name": "Հայերեն",
    "nativeName": "Armenian",
  },
  {
    "tag": "Indonesia",
    "name": "Bahasa",
    "nativeName": "Indonesian",
  },
  {
    "tag": "ig",
    "name": "Igbo",
    "nativeName": "Igbo",
  },
  {
    "tag": "ii",
    "name": "ꆈꌠꁱꂷ",
    "nativeName": "Yi",
  },
  {
    "tag": "is",
    "name": "íslenska",
    "nativeName": "Icelandic",
  },
  {
    "tag": "it",
    "name": "italiano",
    "nativeName": "Italian",
  },
  {
    "tag": "/ᐃᓄᒃᑎᑐᑦ",
    "name": "Inuktitut",
    "nativeName": "Inuktitut",
  },
  {
    "tag": "ja",
    "name": "日本語",
    "nativeName": "Japanese",
  },
  {
    "tag": "ka",
    "name": "ქართული",
    "nativeName": "Georgian",
  },
  {
    "tag": "kk",
    "name": "Қазақша",
    "nativeName": "Kazakh",
  },
  {
    "tag": "kl",
    "name": "kalaallisut",
    "nativeName": "Greenlandic",
  },
  {
    "tag": "km",
    "name": "ខ្មែរ",
    "nativeName": "Khmer",
  },
  {
    "tag": "kn",
    "name": "ಕನ್ನಡ",
    "nativeName": "Kannada",
  },
  {
    "tag": "undefined",
    "name": "한국어/韓國語",
    "nativeName": "Korean",
  },
  {
    "tag": "undefined",
    "name": "ko",
    "nativeName": "조선말/朝鮮말",
  },
  {
    "tag": "kok",
    "name": "कोंकणी",
    "nativeName": "Konkani",
  },
  {
    "tag": "ky",
    "name": "Кыргыз",
    "nativeName": "Kyrgyz",
  },
  {
    "tag": "lb",
    "name": "Lëtzebuergesch",
    "nativeName": "Luxembourgish",
  },
  {
    "tag": "lo",
    "name": "ລາວ",
    "nativeName": "Lao",
  },
  {
    "tag": "lt",
    "name": "lietuvių",
    "nativeName": "Lithuanian",
  },
  {
    "tag": "lv",
    "name": "latviešu",
    "nativeName": "Latvian",
  },
  {
    "tag": "Māori",
    "name": "Reo",
    "nativeName": "Maori",
  },
  {
    "tag": "јазик",
    "name": "македонски",
    "nativeName": "Macedonian",
  },
  {
    "tag": "ml",
    "name": "മലയാളം",
    "nativeName": "Malayalam",
  },
  {
    "tag": "хэл/ᠮᠤᠨᠭᠭᠤᠯ",
    "name": "Монгол",
    "nativeName": "Mongolian",
  },
  {
    "tag": "moh",
    "name": "Kanien'kéha",
    "nativeName": "Mohawk",
  },
  {
    "tag": "mr",
    "name": "मराठी",
    "nativeName": "Marathi",
  },
  {
    "tag": "Malaysia",
    "name": "Bahasa",
    "nativeName": "Malay",
  },
  {
    "tag": "mt",
    "name": "Malti",
    "nativeName": "Maltese",
  },
  {
    "tag": "my",
    "name": "Myanmar",
    "nativeName": "Burmese",
  },
  {
    "tag": "norsk",
    "name": "(Bokmål)",
    "nativeName": "Norwegian",
  },
  {
    "tag": "(नेपाल)",
    "name": "नेपाली",
    "nativeName": "Nepali",
  },
  {
    "tag": "nl",
    "name": "Nederlands",
    "nativeName": "Dutch",
  },
  {
    "tag": "norsk",
    "name": "(Nynorsk)",
    "nativeName": "Norwegian",
  },
  {
    "tag": "no",
    "name": "norsk",
    "nativeName": "Norwegian",
  },
  {
    "tag": "sa",
    "name": "Sesotho",
    "nativeName": "Sesotho",
  },
  {
    "tag": "oc",
    "name": "Occitan",
    "nativeName": "Occitan",
  },
  {
    "tag": "or",
    "name": "ଓଡ଼ିଆ",
    "nativeName": "Odia",
  },
  {
    "tag": "pa",
    "name": "ਪੰਜਾਬੀ",
    "nativeName": "Punjabi",
  },
  {
    "tag": "pl",
    "name": "polski",
    "nativeName": "Polish",
  },
  {
    "tag": "prs",
    "name": "درى",
    "nativeName": "Dari",
  },
  {
    "tag": "ps",
    "name": "پښتو",
    "nativeName": "Pashto",
  },
  {
    "tag": "pt",
    "name": "Português",
    "nativeName": "Portuguese",
  },
  {
    "tag": "quc",
    "name": "K'iche",
    "nativeName": "K'iche",
  },
  {
    "tag": "qu",
    "name": "runasimi",
    "nativeName": "Quechua",
  },
  {
    "tag": "rm",
    "name": "Rumantsch",
    "nativeName": "Romansh",
  },
  {
    "tag": "ro",
    "name": "română",
    "nativeName": "Romanian",
  },
  {
    "tag": "ru",
    "name": "русский",
    "nativeName": "Russian",
  },
  {
    "tag": "rw",
    "name": "Kinyarwanda",
    "nativeName": "Kinyarwanda",
  },
  {
    "tag": "sa",
    "name": "संस्कृत",
    "nativeName": "Sanskrit",
  },
  {
    "tag": "sah",
    "name": "саха",
    "nativeName": "Yakut",
  },
  {
    "tag": "davvisámegiella",
    "name": "(Northern)",
    "nativeName": "Sami",
  },
  {
    "tag": "si",
    "name": "සිංහල",
    "nativeName": "Sinhala",
  },
  {
    "tag": "sk",
    "name": "slovenčina",
    "nativeName": "Slovak",
  },
  {
    "tag": "sl",
    "name": "slovenski",
    "nativeName": "Slovenian",
  },
  {
    "tag": "åarjelsaemiengiele",
    "name": "(Southern)",
    "nativeName": "Sami",
  },
  {
    "tag": "julevusámegiella",
    "name": "(Lule)",
    "nativeName": "Sami",
  },
  {
    "tag": "sämikielâ",
    "name": "(Inari)",
    "nativeName": "Sami",
  },
  {
    "tag": "sääm´ǩiõll",
    "name": "(Skolt)",
    "nativeName": "Sami",
  },
  {
    "tag": "sq",
    "name": "shqipe",
    "nativeName": "Albanian",
  },
  {
    "tag": "sr",
    "name": "srpski/српски",
    "nativeName": "Serbian",
  },
  {
    "tag": "sv",
    "name": "svenska",
    "nativeName": "Swedish",
  },
  {
    "tag": "sw",
    "name": "Kiswahili",
    "nativeName": "Kiswahili",
  },
  {
    "tag": "syc",
    "name": "ܣܘܪܝܝܐ",
    "nativeName": "Syriac",
  },
  {
    "tag": "ta",
    "name": "தமிழ்",
    "nativeName": "Tamil",
  },
  {
    "tag": "te",
    "name": "తెలుగు",
    "nativeName": "Telugu",
  },
  {
    "tag": "tg",
    "name": "Тоҷикӣ",
    "nativeName": "Tajik",
  },
  {
    "tag": "th",
    "name": "ไทย",
    "nativeName": "Thai",
  },
  {
    "tag": "tk",
    "name": "türkmençe",
    "nativeName": "Turkmen",
  },
  {
    "tag": "tn",
    "name": "Setswana",
    "nativeName": "Tswana",
  },
  {
    "tag": "tr",
    "name": "Türkçe",
    "nativeName": "Turkish",
  },
  {
    "tag": "tt",
    "name": "Татарча",
    "nativeName": "Tatar",
  },
  {
    "tag": "tzm",
    "name": "Tamazight",
    "nativeName": "Tamazight",
  },
  {
    "tag": "ug",
    "name": "ئۇيغۇرچە",
    "nativeName": "Uyghur",
  },
  {
    "tag": "uk",
    "name": "українська",
    "nativeName": "Ukrainian",
  },
  {
    "tag": "ur",
    "name": "اُردو",
    "nativeName": "Urdu",
  },
  {
    "tag": "uz",
    "name": "U'zbek/Ўзбек",
    "nativeName": "Uzbek",
  },
  {
    "tag": "Việt/㗂越",
    "name": "Tiếng",
    "nativeName": "Vietnamese",
  },
  {
    "tag": "wo",
    "name": "Wolof",
    "nativeName": "Wolof",
  },
  {
    "tag": "xh",
    "name": "isiXhosa",
    "nativeName": "Xhosa",
  },
  {
    "tag": "yo",
    "name": "Yoruba",
    "nativeName": "Yoruba",
  },
  {
    "tag": "zh",
    "name": "中文",
    "nativeName": "Chinese",
  },
  {
    "tag": "zu",
    "name": "isiZulu",
    "nativeName": "Zulu",
  },
];
List<dynamic> countryCodeOptions = <dynamic>[
  {'name': 'Afghanistan', 'code': 'AF'},
  {'name': 'Åland Islands', 'code': 'AX'},
  {'name': 'Albania', 'code': 'AL'},
  {'name': 'Algeria', 'code': 'DZ'},
  {'name': 'American Samoa', 'code': 'AS'},
  {'name': 'AndorrA', 'code': 'AD'},
  {'name': 'Angola', 'code': 'AO'},
  {'name': 'Anguilla', 'code': 'AI'},
  {'name': 'Antarctica', 'code': 'AQ'},
  {'name': 'Antigua and Barbuda', 'code': 'AG'},
  {'name': 'Argentina', 'code': 'AR'},
  {'name': 'Armenia', 'code': 'AM'},
  {'name': 'Aruba', 'code': 'AW'},
  {'name': 'Australia', 'code': 'AU'},
  {'name': 'Austria', 'code': 'AT'},
  {'name': 'Azerbaijan', 'code': 'AZ'},
  {'name': 'Bahamas', 'code': 'BS'},
  {'name': 'Bahrain', 'code': 'BH'},
  {'name': 'Bangladesh', 'code': 'BD'},
  {'name': 'Barbados', 'code': 'BB'},
  {'name': 'Belarus', 'code': 'BY'},
  {'name': 'Belgium', 'code': 'BE'},
  {'name': 'Belize', 'code': 'BZ'},
  {'name': 'Benin', 'code': 'BJ'},
  {'name': 'Bermuda', 'code': 'BM'},
  {'name': 'Bhutan', 'code': 'BT'},
  {'name': 'Bolivia', 'code': 'BO'},
  {'name': 'Bosnia and Herzegovina', 'code': 'BA'},
  {'name': 'Botswana', 'code': 'BW'},
  {'name': 'Bouvet Island', 'code': 'BV'},
  {'name': 'Brazil', 'code': 'BR'},
  {'name': 'British Indian Ocean Territory', 'code': 'IO'},
  {'name': 'Brunei Darussalam', 'code': 'BN'},
  {'name': 'Bulgaria', 'code': 'BG'},
  {'name': 'Burkina Faso', 'code': 'BF'},
  {'name': 'Burundi', 'code': 'BI'},
  {'name': 'Cambodia', 'code': 'KH'},
  {'name': 'Cameroon', 'code': 'CM'},
  {'name': 'Canada', 'code': 'CA'},
  {'name': 'Cape Verde', 'code': 'CV'},
  {'name': 'Cayman Islands', 'code': 'KY'},
  {'name': 'Central African Republic', 'code': 'CF'},
  {'name': 'Chad', 'code': 'TD'},
  {'name': 'Chile', 'code': 'CL'},
  {'name': 'China', 'code': 'CN'},
  {'name': 'Christmas Island', 'code': 'CX'},
  {'name': 'Cocos (Keeling) Islands', 'code': 'CC'},
  {'name': 'Colombia', 'code': 'CO'},
  {'name': 'Comoros', 'code': 'KM'},
  {'name': 'Congo', 'code': 'CG'},
  {'name': 'Congo, The Democratic Republic of the', 'code': 'CD'},
  {'name': 'Cook Islands', 'code': 'CK'},
  {'name': 'Costa Rica', 'code': 'CR'},
  {'name': 'Cote D\'Ivoire', 'code': 'CI'},
  {'name': 'Croatia', 'code': 'HR'},
  {'name': 'Cuba', 'code': 'CU'},
  {'name': 'Cyprus', 'code': 'CY'},
  {'name': 'Czech Republic', 'code': 'CZ'},
  {'name': 'Denmark', 'code': 'DK'},
  {'name': 'Djibouti', 'code': 'DJ'},
  {'name': 'Dominica', 'code': 'DM'},
  {'name': 'Dominican Republic', 'code': 'DO'},
  {'name': 'Ecuador', 'code': 'EC'},
  {'name': 'Egypt', 'code': 'EG'},
  {'name': 'El Salvador', 'code': 'SV'},
  {'name': 'Equatorial Guinea', 'code': 'GQ'},
  {'name': 'Eritrea', 'code': 'ER'},
  {'name': 'Estonia', 'code': 'EE'},
  {'name': 'Ethiopia', 'code': 'ET'},
  {'name': 'Falkland Islands (Malvinas)', 'code': 'FK'},
  {'name': 'Faroe Islands', 'code': 'FO'},
  {'name': 'Fiji', 'code': 'FJ'},
  {'name': 'Finland', 'code': 'FI'},
  {'name': 'France', 'code': 'FR'},
  {'name': 'French Guiana', 'code': 'GF'},
  {'name': 'French Polynesia', 'code': 'PF'},
  {'name': 'French Southern Territories', 'code': 'TF'},
  {'name': 'Gabon', 'code': 'GA'},
  {'name': 'Gambia', 'code': 'GM'},
  {'name': 'Georgia', 'code': 'GE'},
  {'name': 'Germany', 'code': 'DE'},
  {'name': 'Ghana', 'code': 'GH'},
  {'name': 'Gibraltar', 'code': 'GI'},
  {'name': 'Greece', 'code': 'GR'},
  {'name': 'Greenland', 'code': 'GL'},
  {'name': 'Grenada', 'code': 'GD'},
  {'name': 'Guadeloupe', 'code': 'GP'},
  {'name': 'Guam', 'code': 'GU'},
  {'name': 'Guatemala', 'code': 'GT'},
  {'name': 'Guernsey', 'code': 'GG'},
  {'name': 'Guinea', 'code': 'GN'},
  {'name': 'Guinea-Bissau', 'code': 'GW'},
  {'name': 'Guyana', 'code': 'GY'},
  {'name': 'Haiti', 'code': 'HT'},
  {'name': 'Heard Island and Mcdonald Islands', 'code': 'HM'},
  {'name': 'Holy See (Vatican City State)', 'code': 'VA'},
  {'name': 'Honduras', 'code': 'HN'},
  {'name': 'Hong Kong', 'code': 'HK'},
  {'name': 'Hungary', 'code': 'HU'},
  {'name': 'Iceland', 'code': 'IS'},
  {'name': 'India', 'code': 'IN'},
  {'name': 'Indonesia', 'code': 'ID'},
  {'name': 'Iran, Islamic Republic Of', 'code': 'IR'},
  {'name': 'Iraq', 'code': 'IQ'},
  {'name': 'Ireland', 'code': 'IE'},
  {'name': 'Isle of Man', 'code': 'IM'},
  {'name': 'Israel', 'code': 'IL'},
  {'name': 'Italy', 'code': 'IT'},
  {'name': 'Jamaica', 'code': 'JM'},
  {'name': 'Japan', 'code': 'JP'},
  {'name': 'Jersey', 'code': 'JE'},
  {'name': 'Jordan', 'code': 'JO'},
  {'name': 'Kazakhstan', 'code': 'KZ'},
  {'name': 'Kenya', 'code': 'KE'},
  {'name': 'Kiribati', 'code': 'KI'},
  {'name': 'Korea, Democratic People\'S Republic of', 'code': 'KP'},
  {'name': 'Korea, Republic of', 'code': 'KR'},
  {'name': 'Kuwait', 'code': 'KW'},
  {'name': 'Kyrgyzstan', 'code': 'KG'},
  {'name': 'Lao People\'S Democratic Republic', 'code': 'LA'},
  {'name': 'Latvia', 'code': 'LV'},
  {'name': 'Lebanon', 'code': 'LB'},
  {'name': 'Lesotho', 'code': 'LS'},
  {'name': 'Liberia', 'code': 'LR'},
  {'name': 'Libyan Arab Jamahiriya', 'code': 'LY'},
  {'name': 'Liechtenstein', 'code': 'LI'},
  {'name': 'Lithuania', 'code': 'LT'},
  {'name': 'Luxembourg', 'code': 'LU'},
  {'name': 'Macao', 'code': 'MO'},
  {'name': 'Macedonia, The Former Yugoslav Republic of', 'code': 'MK'},
  {'name': 'Madagascar', 'code': 'MG'},
  {'name': 'Malawi', 'code': 'MW'},
  {'name': 'Malaysia', 'code': 'MY'},
  {'name': 'Maldives', 'code': 'MV'},
  {'name': 'Mali', 'code': 'ML'},
  {'name': 'Malta', 'code': 'MT'},
  {'name': 'Marshall Islands', 'code': 'MH'},
  {'name': 'Martinique', 'code': 'MQ'},
  {'name': 'Mauritania', 'code': 'MR'},
  {'name': 'Mauritius', 'code': 'MU'},
  {'name': 'Mayotte', 'code': 'YT'},
  {'name': 'Mexico', 'code': 'MX'},
  {'name': 'Micronesia, Federated States of', 'code': 'FM'},
  {'name': 'Moldova, Republic of', 'code': 'MD'},
  {'name': 'Monaco', 'code': 'MC'},
  {'name': 'Mongolia', 'code': 'MN'},
  {'name': 'Montserrat', 'code': 'MS'},
  {'name': 'Morocco', 'code': 'MA'},
  {'name': 'Mozambique', 'code': 'MZ'},
  {'name': 'Myanmar', 'code': 'MM'},
  {'name': 'Namibia', 'code': 'NA'},
  {'name': 'Nauru', 'code': 'NR'},
  {'name': 'Nepal', 'code': 'NP'},
  {'name': 'Netherlands', 'code': 'NL'},
  {'name': 'Netherlands Antilles', 'code': 'AN'},
  {'name': 'New Caledonia', 'code': 'NC'},
  {'name': 'New Zealand', 'code': 'NZ'},
  {'name': 'Nicaragua', 'code': 'NI'},
  {'name': 'Niger', 'code': 'NE'},
  {'name': 'Nigeria', 'code': 'NG'},
  {'name': 'Niue', 'code': 'NU'},
  {'name': 'Norfolk Island', 'code': 'NF'},
  {'name': 'Northern Mariana Islands', 'code': 'MP'},
  {'name': 'Norway', 'code': 'NO'},
  {'name': 'Oman', 'code': 'OM'},
  {'name': 'Pakistan', 'code': 'PK'},
  {'name': 'Palau', 'code': 'PW'},
  {'name': 'Palestinian Territory, Occupied', 'code': 'PS'},
  {'name': 'Panama', 'code': 'PA'},
  {'name': 'Papua New Guinea', 'code': 'PG'},
  {'name': 'Paraguay', 'code': 'PY'},
  {'name': 'Peru', 'code': 'PE'},
  {'name': 'Philippines', 'code': 'PH'},
  {'name': 'Pitcairn', 'code': 'PN'},
  {'name': 'Poland', 'code': 'PL'},
  {'name': 'Portugal', 'code': 'PT'},
  {'name': 'Puerto Rico', 'code': 'PR'},
  {'name': 'Qatar', 'code': 'QA'},
  {'name': 'Reunion', 'code': 'RE'},
  {'name': 'Romania', 'code': 'RO'},
  {'name': 'Russian Federation', 'code': 'RU'},
  {'name': 'RWANDA', 'code': 'RW'},
  {'name': 'Saint Helena', 'code': 'SH'},
  {'name': 'Saint Kitts and Nevis', 'code': 'KN'},
  {'name': 'Saint Lucia', 'code': 'LC'},
  {'name': 'Saint Pierre and Miquelon', 'code': 'PM'},
  {'name': 'Saint Vincent and the Grenadines', 'code': 'VC'},
  {'name': 'Samoa', 'code': 'WS'},
  {'name': 'San Marino', 'code': 'SM'},
  {'name': 'Sao Tome and Principe', 'code': 'ST'},
  {'name': 'Saudi Arabia', 'code': 'SA'},
  {'name': 'Senegal', 'code': 'SN'},
  {'name': 'Serbia and Montenegro', 'code': 'CS'},
  {'name': 'Seychelles', 'code': 'SC'},
  {'name': 'Sierra Leone', 'code': 'SL'},
  {'name': 'Singapore', 'code': 'SG'},
  {'name': 'Slovakia', 'code': 'SK'},
  {'name': 'Slovenia', 'code': 'SI'},
  {'name': 'Solomon Islands', 'code': 'SB'},
  {'name': 'Somalia', 'code': 'SO'},
  {'name': 'South Africa', 'code': 'ZA'},
  {'name': 'South Georgia and the South Sandwich Islands', 'code': 'GS'},
  {'name': 'Spain', 'code': 'ES'},
  {'name': 'Sri Lanka', 'code': 'LK'},
  {'name': 'Sudan', 'code': 'SD'},
  {'name': 'Suri', 'code': 'SR'},
  {'name': 'Svalbard and Jan Mayen', 'code': 'SJ'},
  {'name': 'Swaziland', 'code': 'SZ'},
  {'name': 'Sweden', 'code': 'SE'},
  {'name': 'Switzerland', 'code': 'CH'},
  {'name': 'Syrian Arab Republic', 'code': 'SY'},
  {'name': 'Taiwan, Province of China', 'code': 'TW'},
  {'name': 'Tajikistan', 'code': 'TJ'},
  {'name': 'Tanzania, United Republic of', 'code': 'TZ'},
  {'name': 'Thailand', 'code': 'TH'},
  {'name': 'Timor-Leste', 'code': 'TL'},
  {'name': 'Togo', 'code': 'TG'},
  {'name': 'Tokelau', 'code': 'TK'},
  {'name': 'Tonga', 'code': 'TO'},
  {'name': 'Trinidad and Tobago', 'code': 'TT'},
  {'name': 'Tunisia', 'code': 'TN'},
  {'name': 'Turkey', 'code': 'TR'},
  {'name': 'Turkmenistan', 'code': 'TM'},
  {'name': 'Turks and Caicos Islands', 'code': 'TC'},
  {'name': 'Tuvalu', 'code': 'TV'},
  {'name': 'Uganda', 'code': 'UG'},
  {'name': 'Ukraine', 'code': 'UA'},
  {'name': 'United Arab Emirates', 'code': 'AE'},
  {'name': 'United Kingdom', 'code': 'GB'},
  {'name': 'United States', 'code': 'US'},
  {'name': 'United States Minor Outlying Islands', 'code': 'UM'},
  {'name': 'Uruguay', 'code': 'UY'},
  {'name': 'Uzbekistan', 'code': 'UZ'},
  {'name': 'Vanuatu', 'code': 'VU'},
  {'name': 'Venezuela', 'code': 'VE'},
  {'name': 'Viet Nam', 'code': 'VN'},
  {'name': 'Virgin Islands, British', 'code': 'VG'},
  {'name': 'Virgin Islands, U.S.', 'code': 'VI'},
  {'name': 'Wallis and Futuna', 'code': 'WF'},
  {'name': 'Western Sahara', 'code': 'EH'},
  {'name': 'Yemen', 'code': 'YE'},
  {'name': 'Zambia', 'code': 'ZM'},
  {'name': 'Zimbabwe', 'code': 'ZW'}
];
